apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: connector
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Data-Space-Core/ArgoCDTemplate.git
    targetRevision: main
    path: platform-apps/connector
  destination:
    server: https://kubernetes.default.svc
    namespace: connector
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      