apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: omejdn-daps
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml
  - referencegrant.yaml

